package az.technest.whereis.common.error;

public enum ErrorCode {
    VALIDATION_ERROR,
    USER_NOT_FOUND,
    SPACE_NOT_FOUND,
    LOCATION_NOT_FOUND,
    ITEM_NOT_FOUND,
    FILE_NOT_FOUND,
    EMAIL_IN_USE,
    DUPLICATE_NAME,
    INVALID_CREDENTIALS,
    TOKEN_INVALID,
    TOKEN_EXPIRED,
    INVALID_LOCATION_HIERARCHY,
    CYCLE_DETECTED,
    LOCATION_NOT_EMPTY,
    SPACE_NOT_EMPTY,
    FILE_TOO_LARGE,
    UNSUPPORTED_MEDIA_TYPE,
    STORAGE_ERROR,
    AI_UNAVAILABLE,
    AI_NOT_IMPLEMENTED,
    CONFLICT,
    INTERNAL_ERROR
}
